// <auto-generated />
using System;
using FinalProject.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Web.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250607094456_intital")]
    partial class intital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Entities.Models.Ambulance", b =>
                {
                    b.Property<Guid>("AmbulanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AmbulanceId");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmbulanceId");

                    b.ToTable("Ambulances");

                    b.HasData(
                        new
                        {
                            AmbulanceId = new Guid("1f7fc946-ab0a-4c06-8571-3f022559b218"),
                            DriverName = "Ravi Kumar",
                            MobileNumber = "9876543210",
                            VehicleNumber = "UP21 AB 1234",
                            VehicleType = "Normal"
                        },
                        new
                        {
                            AmbulanceId = new Guid("4f4ba941-9355-4335-9cc5-a05226aea4cd"),
                            DriverName = "Sunil Mehra",
                            MobileNumber = "9123456789",
                            VehicleNumber = "UP21 CD 5678",
                            VehicleType = "BasicLifeSupport"
                        },
                        new
                        {
                            AmbulanceId = new Guid("529cdd00-5d9e-475b-af22-e8852ee599ae"),
                            DriverName = "Anil Sharma",
                            MobileNumber = "9012345678",
                            VehicleNumber = "UP21 EF 9012",
                            VehicleType = "AdvancedLifeSupport"
                        },
                        new
                        {
                            AmbulanceId = new Guid("6d7af7dd-7b34-4019-8d25-c73217c0da74"),
                            DriverName = "Vikram Singh",
                            MobileNumber = "9988776655",
                            VehicleNumber = "UP21 GH 3456",
                            VehicleType = "Normal"
                        },
                        new
                        {
                            AmbulanceId = new Guid("841383af-86ff-45e7-ab96-d3b60b1e097f"),
                            DriverName = "Suresh Yadav",
                            MobileNumber = "9876501234",
                            VehicleNumber = "UP21 IJ 7890",
                            VehicleType = "Neonatal"
                        },
                        new
                        {
                            AmbulanceId = new Guid("4a105e1f-397d-465a-832c-8ecdd9d90bc2"),
                            DriverName = "Rajeev Ranjan",
                            MobileNumber = "9123409876",
                            VehicleNumber = "UP21 KL 2345",
                            VehicleType = "AdvancedLifeSupport"
                        },
                        new
                        {
                            AmbulanceId = new Guid("1ce30ccb-f4b4-473a-8222-233a3d27351e"),
                            DriverName = "Manoj Tiwari",
                            MobileNumber = "9001122334",
                            VehicleNumber = "UP21 MN 6789",
                            VehicleType = "Normal"
                        },
                        new
                        {
                            AmbulanceId = new Guid("9ae9403f-961d-4552-bc15-8f2273639640"),
                            DriverName = "Deepak Chauhan",
                            MobileNumber = "9112233445",
                            VehicleNumber = "UP21 OP 1122",
                            VehicleType = "BasicLifeSupport"
                        },
                        new
                        {
                            AmbulanceId = new Guid("57d695f7-4cc6-48c6-bd78-1a5bc96b3a53"),
                            DriverName = "Karan Verma",
                            MobileNumber = "9223344556",
                            VehicleNumber = "UP21 QR 3344",
                            VehicleType = "AdvancedLifeSupport"
                        },
                        new
                        {
                            AmbulanceId = new Guid("1b84996d-e7c2-4c96-aa39-f111eb5304a5"),
                            DriverName = "Amit Joshi",
                            MobileNumber = "9334455667",
                            VehicleNumber = "UP21 ST 5566",
                            VehicleType = "Normal"
                        });
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HODName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneExtensionNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DeptName = "Cardiology",
                            HODName = "Dr. Anil Mehra",
                            PhoneExtensionNo = "111"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DeptName = "Neurology",
                            HODName = "Dr. Seema Verma",
                            PhoneExtensionNo = "222"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DeptName = "Orthopedics",
                            HODName = "Dr. Rajesh Khanna",
                            PhoneExtensionNo = "333"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DeptName = "Pediatrics",
                            HODName = "Dr. Neha Sharma",
                            PhoneExtensionNo = "444"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DeptName = "General Medicine",
                            HODName = "Dr. Vivek Gupta",
                            PhoneExtensionNo = "555"
                        });
                });

            modelBuilder.Entity("FinalProject.Entities.Models.DischargedPatient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AdmissionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DischargeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoomNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DischargedPatients", (string)null);
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AadharNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("aad9f233-2c61-4dc3-9b45-c5da6815ad7d"),
                            AadharNo = "123456789012",
                            Age = 45,
                            DepartmentId = 1,
                            EmailId = "ramesh.kumar@hospital.com",
                            Gender = "Male",
                            MobileNumber = "9876543210",
                            Name = "Dr. Ramesh Kumar",
                            Position = "Senior Cardiologist"
                        },
                        new
                        {
                            EmployeeId = new Guid("62989037-c514-420a-aaad-0534383cffa3"),
                            AadharNo = "234567890123",
                            Age = 38,
                            DepartmentId = 2,
                            EmailId = "priya.sharma@hospital.com",
                            Gender = "Female",
                            MobileNumber = "9123456789",
                            Name = "Dr. Priya Sharma",
                            Position = "Neurologist"
                        },
                        new
                        {
                            EmployeeId = new Guid("9d911f68-d7e1-40fb-8255-254f23105bc3"),
                            AadharNo = "345678901234",
                            Age = 50,
                            DepartmentId = 3,
                            EmailId = "arvind.patel@hospital.com",
                            Gender = "Male",
                            MobileNumber = "9012345678",
                            Name = "Dr. Arvind Patel",
                            Position = "Orthopedic Surgeon"
                        },
                        new
                        {
                            EmployeeId = new Guid("8a8affcc-c224-4f3b-a49e-6446c9e8329d"),
                            AadharNo = "456789012345",
                            Age = 42,
                            DepartmentId = 4,
                            EmailId = "sneha.verma@hospital.com",
                            Gender = "Female",
                            MobileNumber = "9988776655",
                            Name = "Dr. Sneha Verma",
                            Position = "Pediatrician"
                        },
                        new
                        {
                            EmployeeId = new Guid("d1c1c324-b11c-42b5-9db0-ebea2b566d89"),
                            AadharNo = "567890123456",
                            Age = 47,
                            DepartmentId = 5,
                            EmailId = "manish.gupta@hospital.com",
                            Gender = "Male",
                            MobileNumber = "9876501234",
                            Name = "Dr. Manish Gupta",
                            Position = "General Physician"
                        },
                        new
                        {
                            EmployeeId = new Guid("64537262-c51a-41c1-9994-06cb1d2d5d78"),
                            AadharNo = "678901234567",
                            Age = 40,
                            DepartmentId = 1,
                            EmailId = "kavita.nair@hospital.com",
                            Gender = "Female",
                            MobileNumber = "9112233445",
                            Name = "Dr. Kavita Nair",
                            Position = "Cardiology Consultant"
                        },
                        new
                        {
                            EmployeeId = new Guid("d26f37a7-8ff1-45b5-84e0-61e032de441f"),
                            AadharNo = "789012345678",
                            Age = 36,
                            DepartmentId = 2,
                            EmailId = "rohit.sinha@hospital.com",
                            Gender = "Male",
                            MobileNumber = "9223344556",
                            Name = "Dr. Rohit Sinha",
                            Position = "Neurosurgeon"
                        },
                        new
                        {
                            EmployeeId = new Guid("8f647e4c-f09b-4aa5-90ae-2f16d883b65f"),
                            AadharNo = "890123456789",
                            Age = 44,
                            DepartmentId = 3,
                            EmailId = "meena.joshi@hospital.com",
                            Gender = "Female",
                            MobileNumber = "9334455667",
                            Name = "Dr. Meena Joshi",
                            Position = "Orthopedic Consultant"
                        },
                        new
                        {
                            EmployeeId = new Guid("048a035c-adc0-4eee-a9c5-ed320cfa4c27"),
                            AadharNo = "901234567890",
                            Age = 39,
                            DepartmentId = 4,
                            EmailId = "nikhil.bansal@hospital.com",
                            Gender = "Male",
                            MobileNumber = "9445566778",
                            Name = "Dr. Nikhil Bansal",
                            Position = "Child Specialist"
                        },
                        new
                        {
                            EmployeeId = new Guid("7c8ed9e7-0e96-4b45-91b5-cba7b99a1d0f"),
                            AadharNo = "012345678901",
                            Age = 41,
                            DepartmentId = 5,
                            EmailId = "anuja.desai@hospital.com",
                            Gender = "Female",
                            MobileNumber = "9556677889",
                            Name = "Dr. Anuja Desai",
                            Position = "General Medicine Consultant"
                        });
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AadharId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("AdmissionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDischarged")
                        .HasColumnType("bit");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("roomId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = new Guid("c513f843-93ea-4761-9113-3eb19b910122"),
                            AadharId = "123456789012",
                            AdmissionDateTime = new DateTime(2025, 5, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Diabetes",
                            FirstName = "Amit",
                            Gender = "Male",
                            InitialDeposit = 5000m,
                            LastName = "Sharma",
                            MobileNumber = "9876543210",
                            Symptoms = "Fatigue, frequent urination",
                            isDischarged = false,
                            roomId = 115
                        });
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 101L);

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 101,
                            BedType = "Single",
                            IsAvailable = false,
                            Price = 1000m,
                            RoomNumber = "A101"
                        },
                        new
                        {
                            RoomId = 102,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2000m,
                            RoomNumber = "A102"
                        },
                        new
                        {
                            RoomId = 103,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1500m,
                            RoomNumber = "A103"
                        },
                        new
                        {
                            RoomId = 104,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 1800m,
                            RoomNumber = "A104"
                        },
                        new
                        {
                            RoomId = 105,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1200m,
                            RoomNumber = "A105"
                        },
                        new
                        {
                            RoomId = 106,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2100m,
                            RoomNumber = "B101"
                        },
                        new
                        {
                            RoomId = 107,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2200m,
                            RoomNumber = "B102"
                        },
                        new
                        {
                            RoomId = 108,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1300m,
                            RoomNumber = "B103"
                        },
                        new
                        {
                            RoomId = 109,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1700m,
                            RoomNumber = "B104"
                        },
                        new
                        {
                            RoomId = 110,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 1600m,
                            RoomNumber = "B105"
                        },
                        new
                        {
                            RoomId = 111,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1900m,
                            RoomNumber = "C101"
                        },
                        new
                        {
                            RoomId = 112,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2000m,
                            RoomNumber = "C102"
                        },
                        new
                        {
                            RoomId = 113,
                            BedType = "Single",
                            IsAvailable = true,
                            Price = 1400m,
                            RoomNumber = "C103"
                        },
                        new
                        {
                            RoomId = 114,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2300m,
                            RoomNumber = "C104"
                        },
                        new
                        {
                            RoomId = 115,
                            BedType = "Double",
                            IsAvailable = true,
                            Price = 2500m,
                            RoomNumber = "C105"
                        });
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Employee", b =>
                {
                    b.HasOne("FinalProject.Entities.Models.Department", "Department")
                        .WithMany("EmpaneledDoctorNames")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Patient", b =>
                {
                    b.HasOne("FinalProject.Entities.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FinalProject.Entities.Models.Department", b =>
                {
                    b.Navigation("EmpaneledDoctorNames");
                });
#pragma warning restore 612, 618
        }
    }
}
